DROP TABLE IF EXISTS AUTH;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_username VARCHAR(255) NOT NULL,
    user_password VARCHAR(255) NOT NULL,
    user_role VARCHAR(25) NOT NULL
);